// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// distmat
NumericMatrix distmat(NumericVector id, NumericVector x, NumericVector y, int n);
RcppExport SEXP mta_distmat(SEXP idSEXP, SEXP xSEXP, SEXP ySEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(distmat(id, x, y, n));
    return __result;
END_RCPP
}
// rootChoose
double rootChoose(int n, int k, double root);
RcppExport SEXP mta_rootChoose(SEXP nSEXP, SEXP kSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type root(rootSEXP);
    __result = Rcpp::wrap(rootChoose(n, k, root));
    return __result;
END_RCPP
}
// rootChooseLookup
double rootChooseLookup(int n, int k, std::vector<double> lookup);
RcppExport SEXP mta_rootChooseLookup(SEXP nSEXP, SEXP kSEXP, SEXP lookupSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type lookup(lookupSEXP);
    __result = Rcpp::wrap(rootChooseLookup(n, k, lookup));
    return __result;
END_RCPP
}
// lookup
std::vector<double> lookup(int n, double root);
RcppExport SEXP mta_lookup(SEXP nSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type root(rootSEXP);
    __result = Rcpp::wrap(lookup(n, root));
    return __result;
END_RCPP
}
// rootCombLookup
double rootCombLookup(std::vector<double> ns, std::vector<double> lookup);
RcppExport SEXP mta_rootCombLookup(SEXP nsSEXP, SEXP lookupSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<double> >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type lookup(lookupSEXP);
    __result = Rcpp::wrap(rootCombLookup(ns, lookup));
    return __result;
END_RCPP
}
// stabExp
double stabExp(std::vector<double> ns, std::vector<double> lookup);
RcppExport SEXP mta_stabExp(SEXP nsSEXP, SEXP lookupSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<double> >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type lookup(lookupSEXP);
    __result = Rcpp::wrap(stabExp(ns, lookup));
    return __result;
END_RCPP
}
// f_rescale_c
NumericMatrix f_rescale_c(NumericVector x, NumericVector y, int npts);
RcppExport SEXP mta_f_rescale_c(SEXP xSEXP, SEXP ySEXP, SEXP nptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type npts(nptsSEXP);
    __result = Rcpp::wrap(f_rescale_c(x, y, npts));
    return __result;
END_RCPP
}
// spatialRescale_c
NumericMatrix spatialRescale_c(GenericVector trs, int npts);
RcppExport SEXP mta_spatialRescale_c(SEXP trsSEXP, SEXP nptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< GenericVector >::type trs(trsSEXP);
    Rcpp::traits::input_parameter< int >::type npts(nptsSEXP);
    __result = Rcpp::wrap(spatialRescale_c(trs, npts));
    return __result;
END_RCPP
}
